import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Github, Loader2, Sparkles, Send, AlertCircle } from 'lucide-react';
import { Layout } from '@/components/Layout';
import { useAuth } from '@/contexts/AuthContext';
import { addProject } from '@/lib/firebase';
import { fetchGitHubStats, calculateVitalityScore, GitHubRepoStats } from '@/lib/github';
import { generateGhostLog } from '@/lib/gemini';
import { toast } from 'sonner';
import { Link } from 'react-router-dom';

const GhostProject = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  
  const [formData, setFormData] = useState({
    title: '',
    githubUrl: '',
    creatorName: '',
    creatorEmail: '',
  });
  
  const [repoStats, setRepoStats] = useState<GitHubRepoStats | null>(null);
  const [ghostLog, setGhostLog] = useState('');
  const [vitalityScore, setVitalityScore] = useState(0);
  const [projectStatus, setProjectStatus] = useState<'active' | 'dormant' | 'haunted'>('dormant');
  
  const [fetchingStats, setFetchingStats] = useState(false);
  const [generatingLog, setGeneratingLog] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  const handleFetchStats = async () => {
    if (!formData.githubUrl) {
      toast.error('Please enter a GitHub URL first');
      return;
    }

    setFetchingStats(true);
    try {
      const stats = await fetchGitHubStats(formData.githubUrl);
      if (stats) {
        setRepoStats(stats);
        const score = calculateVitalityScore(stats);
        setVitalityScore(score);
        
        // Auto-fill title if empty
        if (!formData.title) {
          setFormData(prev => ({ ...prev, title: stats.name }));
        }
        
        toast.success('Repository stats fetched successfully');
      } else {
        toast.error('Failed to fetch repository stats. Check the URL.');
      }
    } catch (error) {
      toast.error('Error fetching GitHub stats');
    } finally {
      setFetchingStats(false);
    }
  };

  const handleGenerateGhostLog = async () => {
    if (!repoStats) {
      toast.error('Fetch repository stats first');
      return;
    }

    setGeneratingLog(true);
    try {
      const result = await generateGhostLog(
        repoStats.name,
        repoStats.description,
        {
          stars: repoStats.stars,
          forks: repoStats.forks,
          lastUpdated: repoStats.lastUpdated,
        }
      );
      
      setGhostLog(result.ghostLog);
      setProjectStatus(result.status);
      toast.success('Ghost Log generated by AI');
    } catch (error) {
      toast.error('Failed to generate Ghost Log');
    } finally {
      setGeneratingLog(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!ghostLog) {
      toast.error('Please generate a Ghost Log first');
      return;
    }

    setSubmitting(true);
    try {
      await addProject({
        title: formData.title,
        githubUrl: formData.githubUrl,
        creatorName: formData.creatorName,
        creatorEmail: formData.creatorEmail,
        ghostLog,
        vitalityScore,
        status: projectStatus,
        stars: repoStats?.stars || 0,
        forks: repoStats?.forks || 0,
        lastUpdated: repoStats?.lastUpdated || new Date().toISOString(),
      });

      toast.success('Project submitted to the Ghost Vault!');
      navigate('/vault');
    } catch (error) {
      console.error('Error submitting project:', error);
      toast.error('Failed to submit project. Please try again.');
    } finally {
      setSubmitting(false);
    }
  };

  if (!user) {
    return (
      <Layout>
        <div className="min-h-screen flex items-center justify-center p-8">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="cyber-card text-center max-w-md"
          >
            <AlertCircle className="w-16 h-16 text-primary mx-auto mb-4" />
            <h2 className="text-2xl font-bold mb-4 neon-text">Authentication Required</h2>
            <p className="text-muted-foreground mb-6">
              You need to sign in to submit projects to the Ghost Vault.
            </p>
            <Link to="/auth" className="cyber-button inline-block">
              Initialize Connection
            </Link>
          </motion.div>
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="min-h-screen p-8">
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="max-w-3xl mx-auto"
        >
          <h1 className="text-4xl font-bold neon-text-intense mb-4">Ghost a Project</h1>
          <p className="text-muted-foreground mb-8">
            Submit a project to the Ghost Vault. Our AI will analyze it and generate a Ghost Log.
          </p>

          <form onSubmit={handleSubmit} className="space-y-6">
            {/* GitHub URL */}
            <div className="cyber-card">
              <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                <Github className="w-5 h-5" />
                Repository Information
              </h3>
              
              <div className="space-y-4">
                <div>
                  <label className="block text-sm text-muted-foreground mb-2">GitHub URL</label>
                  <div className="flex gap-2">
                    <input
                      type="url"
                      value={formData.githubUrl}
                      onChange={(e) => setFormData({ ...formData, githubUrl: e.target.value })}
                      className="cyber-input flex-1"
                      placeholder="https://github.com/user/repo"
                      required
                    />
                    <button
                      type="button"
                      onClick={handleFetchStats}
                      disabled={fetchingStats}
                      className="cyber-button flex items-center gap-2"
                    >
                      {fetchingStats ? (
                        <Loader2 className="w-4 h-4 animate-spin" />
                      ) : (
                        <Github className="w-4 h-4" />
                      )}
                      Fetch
                    </button>
                  </div>
                </div>

                {repoStats && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    className="p-4 bg-secondary rounded-lg space-y-2"
                  >
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">Stars:</span>
                      <span className="text-foreground">{repoStats.stars}</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">Forks:</span>
                      <span className="text-foreground">{repoStats.forks}</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">Language:</span>
                      <span className="text-foreground">{repoStats.language}</span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">Last Updated:</span>
                      <span className="text-foreground">
                        {new Date(repoStats.lastUpdated).toLocaleDateString()}
                      </span>
                    </div>
                    <div className="flex justify-between text-sm">
                      <span className="text-muted-foreground">Vitality Score:</span>
                      <span className="text-primary font-bold">{vitalityScore}%</span>
                    </div>
                  </motion.div>
                )}

                <div>
                  <label className="block text-sm text-muted-foreground mb-2">Project Title</label>
                  <input
                    type="text"
                    value={formData.title}
                    onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                    className="cyber-input w-full"
                    placeholder="Project name"
                    required
                  />
                </div>
              </div>
            </div>

            {/* Ghost Log Generation */}
            <div className="cyber-card">
              <h3 className="text-lg font-bold mb-4 flex items-center gap-2">
                <Sparkles className="w-5 h-5" />
                AI Ghost Log
              </h3>
              
              <div className="space-y-4">
                <button
                  type="button"
                  onClick={handleGenerateGhostLog}
                  disabled={!repoStats || generatingLog}
                  className="cyber-button w-full flex items-center justify-center gap-2"
                >
                  {generatingLog ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Channeling spirits...
                    </>
                  ) : (
                    <>
                      <Sparkles className="w-4 h-4" />
                      Generate Ghost Log
                    </>
                  )}
                </button>

                {ghostLog && (
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="p-4 bg-secondary rounded-lg"
                  >
                    <p className="text-foreground italic">"{ghostLog}"</p>
                    <div className="mt-3 flex items-center gap-2">
                      <span className="text-xs text-muted-foreground">Status:</span>
                      <span className={`text-xs px-2 py-1 rounded uppercase ${
                        projectStatus === 'active' 
                          ? 'bg-primary/20 text-primary' 
                          : projectStatus === 'dormant'
                          ? 'bg-yellow-500/20 text-yellow-500'
                          : 'bg-destructive/20 text-destructive'
                      }`}>
                        {projectStatus}
                      </span>
                    </div>
                  </motion.div>
                )}
              </div>
            </div>

            {/* Creator Information */}
            <div className="cyber-card">
              <h3 className="text-lg font-bold mb-4">Creator Information</h3>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm text-muted-foreground mb-2">Your Name</label>
                  <input
                    type="text"
                    value={formData.creatorName}
                    onChange={(e) => setFormData({ ...formData, creatorName: e.target.value })}
                    className="cyber-input w-full"
                    placeholder="John Doe"
                    required
                  />
                </div>
                <div>
                  <label className="block text-sm text-muted-foreground mb-2">Your Email</label>
                  <input
                    type="email"
                    value={formData.creatorEmail}
                    onChange={(e) => setFormData({ ...formData, creatorEmail: e.target.value })}
                    className="cyber-input w-full"
                    placeholder="john@example.com"
                    required
                  />
                </div>
              </div>
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              disabled={submitting || !ghostLog}
              className="cyber-button w-full text-lg py-4 flex items-center justify-center gap-2"
            >
              {submitting ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Transmitting to Vault...
                </>
              ) : (
                <>
                  <Send className="w-5 h-5" />
                  Submit to Ghost Vault
                </>
              )}
            </button>
          </form>
        </motion.div>
      </div>
    </Layout>
  );
};

export default GhostProject;
